---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ledger-api-secrets
  namespace: payments
spec:
  encryptedData:
    DB_PASSWORD: AgCZ+aSk/cwbzh728XzX8LHTB2f4hLSOF8yqj9ug9QPtAi5L94yNH1LNqiY2HsNkF44mo6wHP9vPm9gA9wsa3oGEtdR5wvrizrtJ8QFnfYrbMgGbueEFl+scq4CcBhGC6KWxbOYUOA1T/t0USuQob33+6AmDK8Q27fKBLvAgZmpM+omfjaCsE/qH2JfQts/i/LojhhXzeDnSZ9PDKadJpfB28MCQwrNTgh/nN59MYGW9zCPKN3MVADw4o7yLWvGiWFD4MoQvJQS3Ib7tRrVo9rXrSOJNe0B5eCx4hnKsF5tl9tdnrQns1swZGw1UBumwh8U4mXestyAkVDPxSzdP0fYfD1BS94Alq33DyzUPz4hAC4wdQr4piPjmi+YWa9hlb9GOF5H7CzK5Jzv49Yl0cBijrX8ANLT5P+hxzE6eBUxarzSebGguIxZ1wKEuXF9z77gbJlbLMzV+sDe7WFJWQELcyvjiG0BO+8n+JRgoyjkonBlPe7I9IYJW2d+PblZDCvfALUlXeqS54W1OiBJL3TOBAza+7ZqWDhRb6GBPxU0FPxARe8I2lCYVfR+Sa3Yh890SeqyKZyaDARUNOeEOtsIHga6B0WlSvj0HX9I99HejpYfOQmlnxopCR7lrCNAMpFHerxBAbjK8O2lQO53QVjcvmqDyKTJn+83jRJOq1/21TRY5AkfGzmoCtMYmGlXAZqN8W+DXcMQCEKKlMg==
    STRIPE_API_KEY: AgChyA0oGZwwlnAF7dcd5w4HemzO4DT8KwZ7GTJ/dYDIrSvNjupWzr+si3VLm4uxzxRsUibfxCQMZfc6I/LzUf56sLelqM/GLIR4mVoW7xRMZJug3suld0KamAGfF9M2riyZurqIsQj0IBt+SwYLX+u0L9jwugaKf3GE//2wvTbfnkujVH4OJbRE0+ZO3oqWNicBZv4KOPuhzj8x3alUFQgaIXu0rSUHSJpv+nuFiYvI5/6DQSh9oeuklG5Jtsg00qw3Z4XOff3OGoZ7qbow5vIQtiLLo/GBg/ww68Ukqo2+5RAkS/KT+RYXw7fP36AylxfxmbKIpMIqD+v+no6YOxe7FGVEhgxzSjrBnKiIz75Eq0lWKgTSK+pWdpYpQCp697DRLvRu4RptM/hxa/I2In3bds+KsgCmp3ObuR507XLwD6BZe3/yRLCPXUn/7Py8y4nYv9sKTewAFSnR/faAtUzb2surTLS1xgmNlwyzEPtueiIUm5W75AQkaDIqPacxIgDhJPbrh6SCjsLjQAdEcQzbbRfNERiYL5EWauWSz27a962k/l8hRF1i9SL+aH32hVg1XoCrorBGxYYSruFOe0vartrW3lgYZNjoDkS4CeMqQkfePOIlrO+l7KT+blP4z1uVs2WqCMrQm23qKNfv92PXY+y2ke2Q1qAVhDdxTujrb6shly1hmV+XG52Kk/sYchet3EqO6O971jGsdl9ugAdbE3O3fwWxciRTwtYySw==
  template:
    metadata:
      creationTimestamp: null
      name: ledger-api-secrets
      namespace: payments
